name: Update CS50W Progress

on:
  push:
    paths:
      - 'cs50w/status.json'
  workflow_dispatch:

jobs:
  update-cs50:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update README with CS50W progress
        run: |
          python .github/scripts/cs50w_update_progress.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CS50W progress in README"
          git push