name: Update Progress

on:
  push:
    branches: [ main ]
    paths:
      - '*/README.md'
      - '*/status.json'
  workflow_dispatch:

jobs:
  update-main-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update main README with course progress
        run: |
          python .github/scripts/update_progress.py
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update progress in README"
          git push